#ifndef METAPHYSICL_NUMERIC_LIMITS
#define METAPHYSICL_NUMERIC_LIMITS

#include <limits>

namespace MetaPhysicL {
template <typename T> class numeric_limits;

#define DEFINE_METAPHYSICL_NUMERIC_LIMITS(TYPE)                                \
  template <> class numeric_limits<TYPE> : public std::numeric_limits<TYPE> {}

DEFINE_METAPHYSICL_NUMERIC_LIMITS(bool);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(char);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(signed char);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(unsigned char);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(wchar_t);
// DEFINE_METAPHYSICL_NUMERIC_LIMITS(char8_t); (since C++20)
DEFINE_METAPHYSICL_NUMERIC_LIMITS(char16_t);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(char32_t);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(short);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(unsigned short);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(int);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(unsigned int);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(long);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(unsigned long);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(long long);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(unsigned long long);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(float);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(double);
DEFINE_METAPHYSICL_NUMERIC_LIMITS(long double);
} // namespace MetaPhysicL

#endif // METAPHYSICL_NUMERIC_LIMITS
